port: 4000
db:
    Mysql:
        -   enabled: true
            host: localhost
            port: 27017
            username: test
            password: 12345
            database: demo
            nameconn: connMysql
            lang: ES